[build]
  command = "gem install bundler && bundle install && jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.2"  # Specify the Ruby version to use
  BUNDLE_WITHOUT = "development test"  # Exclude unnecessary groups