name: Update Videos on GitHub Pages

on:
  schedule:
    # This runs every day at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update_videos:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies for downloading videos
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Download the videos
      - name: Download videos
        run: |
          mkdir -p /assets/videos
          python -c "
import requests
import os

# List of video URLs
urls = [
    'https://img.nsmc.org.cn/CLOUDIMAGE/GEOS/MOS/IRX/VIDEO/GEOS.MOS.IRX.GBAL.24h.mp4',
    'https://img.nsmc.org.cn/CLOUDIMAGE/GEOS/MOS/IRX/VIDEO/GEOS.MOS.IRX.GBAL.72h.mp4',
    'https://img.nsmc.org.cn/CLOUDIMAGE/FY4B/AGRI/GCLR/VIDEO/FY4B.disk.gclr.24h.mp4',
    'https://img.nsmc.org.cn/CLOUDIMAGE/FY4B/AGRI/GCLR/VIDEO/FY4B.disk.gclr.72h.mp4',
    'https://img.nsmc.org.cn/CLOUDIMAGE/FY2H/VIDEO/FY2H.br.72h.mp4',
    'https://agora.ex.nii.ac.jp/digital-typhoon/latest/animation/MP4/last-024h.mp4',
    'https://agora.ex.nii.ac.jp/digital-typhoon/latest/animation/MP4/last-240h.mp4'
]

# Download each video
for url in urls:
    file_name = os.path.join('assets', 'videos', os.path.basename(url))
    print(f"Downloading {url}...")
    response = requests.get(url)
    with open(file_name, 'wb') as f:
        f.write(response.content)
          "

      # Step 5: Commit and push changes
      - name: Git commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/videos/*.mp4
          git commit -m "Automated video update"
          git push origin main
